import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Menu } from '@/components/Menu';
import DialogueList from '@/components/DialogueList';
import ChatInput from '@/components/ChatInput';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>QChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <div className="w-4/12 bg-amber-500 h-screen">
          <Menu />
          <DialogueList />
        </div>

        <div className="w-8/12  h-screen flex flex-col">
          <div className="chat-header bg-neutral-400 h-16"></div>
          <div className="chat-main bg-fuchsia-600 h-full flex flex-col items-center">
            {/* костьіль */}
            <section className="chat-bubbles w-2/3 bg-green-400 mb-2" style={{ height: '88%' }}>
              <div></div>
            </section>

            <ChatInput />
          </div>
        </div>
      </main>
    </>
  );
}
