import Head from 'next/head';
import ChatInput from '@/components/ChatWindow/ChatInput';
import ChatBubblesContainer from '@/components/ChatWindow/ChatBubblesContainer';
import ChatHeader from '@/components/ChatWindow/ChatHeader';
import Menu from '@/components/LeftMenu/Menu';
import ChatWindow from '@/components/ChatWindow/ChatWindow';

export default function Home() {
  return (
    <>
      <Head>
        <title>QChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <Menu />

        <div className="w-8/12 flex flex-col h-screen relative">
          <ChatHeader />
          <ChatWindow/>
        </div>
      </main>
    </>
  );
}
